/**
 * Item bank (illustrative). In production these are generated by the content
 * pipeline (§14.2) and human-approved before any child sees them; here we
 * synthesize auto-checkable concept items from the curriculum graph so the
 * mastery loop is genuinely interactive without a backend.
 *
 * Behind the ItemProvider port so the real generator/AI gateway swaps in.
 */
import type { CurriculumGraph } from "../../curriculum/graph";
import type { Unit } from "../../domain/curriculum";
import type { AiInteractionStyle } from "../../domain/curriculum";
import { hashSeed, makeRng, shuffle } from "../rng";

export type ItemKind = "check" | "practice" | "summation" | "retention";

export interface Item {
  id: string;
  kind: ItemKind;
  prompt: string;
  choices: string[];
  correctIndex: number;
  conceptNodeTitle: string;
  aiFree: boolean; // summation + retention scoring are AI-free (§7)
}

export interface ItemProvider {
  build(unit: Unit, kind: ItemKind, count: number, salt?: string): Item[];
}

const CHECK_STEM: Record<AiInteractionStyle, (u: string) => string> = {
  "intro-questions-responses": (u) => `Quick check — which idea belongs to “${u}”?`,
  "experiment-simulation": (u) => `In our work on “${u}”, which idea are we investigating?`,
  "story-narrative": (u) => `In today's story about “${u}”, which idea fits?`,
  "conversational-phonics-reading": (u) => `Reading focus — which skill belongs to “${u}”?`,
};

export class GraphItemBank implements ItemProvider {
  /** Distractor pool: concept titles grouped by subject (prefer cross-subject wrongs). */
  private poolBySubject = new Map<string, string[]>();
  private allTitles: string[] = [];

  constructor(private graph: CurriculumGraph) {
    for (const u of graph.allUnits) {
      const list = this.poolBySubject.get(u.subjectKey) ?? [];
      for (const n of u.conceptNodes) {
        list.push(n.title);
        this.allTitles.push(n.title);
      }
      this.poolBySubject.set(u.subjectKey, list);
    }
  }

  build(unit: Unit, kind: ItemKind, count: number, salt = ""): Item[] {
    const style = this.graph.subject(unit.subjectKey)?.aiInteractionStyle ?? "intro-questions-responses";
    const rng = makeRng(hashSeed(`${unit.id}:${kind}:${salt}`));
    const nodeTitles = unit.conceptNodes.map((n) => n.title);
    if (nodeTitles.length === 0) return [];

    // Distractors: titles from other subjects (clearly not this unit).
    const otherTitles = this.allTitles.filter(
      (t) => !nodeTitles.includes(t),
    );

    const items: Item[] = [];
    const nodesShuffled = shuffle(rng, nodeTitles);
    for (let i = 0; i < count; i++) {
      const correct = nodesShuffled[i % nodesShuffled.length];
      const distractors = shuffle(rng, otherTitles).slice(0, 3);
      const choices = shuffle(rng, [correct, ...distractors]);
      const stem =
        kind === "check"
          ? CHECK_STEM[style](unit.title)
          : kind === "summation"
            ? `Mastery proof (AI-free) — which statement is part of “${unit.title}”?`
            : kind === "retention"
              ? `Retention check — which idea belongs to “${unit.title}”?`
              : `Practising “${unit.title}” — pick the idea that belongs to this unit.`;
      items.push({
        id: `${unit.id}-${kind}-${salt}-${i}`,
        kind,
        prompt: stem,
        choices,
        correctIndex: choices.indexOf(correct),
        conceptNodeTitle: correct,
        aiFree: kind === "summation" || kind === "retention",
      });
    }
    return items;
  }
}
